<PROGRAM> = <BEGIN> <MAIN_PROGRAM> <END>

<MAIN_PROGRAM> = <THINGS> <END_LINE> <MAIN_PROGRAM_>

<MAIN_PROGRAM_> = <MAIN_PROGRAM>
<MAIN_PROGRAM_> = <EPISILON>

<THINGS> = <FUNCTION_CALL>
<THINGS> = <EXPRESSION>
<THINGS> = <VARIABLE_DECLARATION>
<THINGS> = <VARIABLE_ATTRIBUTION>

<VARIABLE_DECLARATION> = <TYPE> <IDENTIFIER_SEQUENCE> 

<VARIABLE_ATTRIBUTION> = <IDENTIFIER> <ATTRIBUITING_OPERATOR> <BASIC_ELEMENTS>

<IDENTIFIER_SEQUENCE> = <IDENTIFIER> <IDENTIFIER_SEQUENCE_>
<IDENTIFIER_SEQUENCE_> = <VARIABLE_SEPARATOR> <IDENTIFIER_SEQUENCE>
<IDENTIFIER_SEQUENCE_> = <EPISILON> 

<FUNCTION_CALL> = <FUNCTION_OPEN> <FUNCTION_CLOSE>

<FUNCTION_OPEN> = <FUNCTION_SEPARATOR> <IDENTIFIER> <PRIMARY_SEPARATOR_OPEN> 

<FUNCTION_CLOSE> = <FUNCTION_CALL_ARGS> <PRIMARY_SEPARATOR_CLOSE>
<FUNCTION_CLOSE> = <PRIMARY_SEPARATOR_CLOSE>

<FUNCTION_CALL_ARGS> = <BASIC_ELEMENTS> <MORE_ARGS> 

<MORE_ARGS> = <VARIABLE_SEPARATOR> <FUNCTION_CALL_ARGS>
<MORE_ARGS> = <EPISILON>

<VARIABLE_SEPARATOR> = ,

<EXPRESSION> = <PRIMARY_SEPARATOR_OPEN> <BASIC_ELEMENTS> <OPERATOR> <BASIC_ELEMENTS> <PRIMARY_SEPARATOR_CLOSE>

<OPERATOR> = <BASIC_OPERATOR>
<OPERATOR> = <COMPLEX_OPERATOR>

<BASIC_OPERATOR> = -
<BASIC_OPERATOR> = +

<COMPLEX_OPERATOR> = /
<COMPLEX_OPERATOR> = *

<ATTRIBUITING_OPERATOR> = =

<BASIC_ELEMENTS> = <NUMBER>
<BASIC_ELEMENTS> = <EXPRESSION>

<BASIC_ELEMENTS> = <IDENTIFIER> 
<BASIC_ELEMENTS> = <FUNCTION_CALL> 

<PRIMARY_SEPARATOR_OPEN> = (
<PRIMARY_SEPARATOR_CLOSE> = )

<NUMBER> = a
<IDENTIFIER> = b
<END_LINE> = ;
<EPISILON> =  ε
<FUNCTION_SEPARATOR> = #
<BEGIN> = INICIO
<END> = FIM
<TYPE> = BOOLEAN
<TYPE> = NUMERO
<TYPE> = TEXTO

