<PROGRAM> = BEGIN <BLOCO> END

<BLOCO> = é
<BLOCO> = <BLOCO_INICIO> <BLOCO_FIM>

<BLOCO_INICIO> = <EXPRESSAO_ATT>
<BLOCO_FIM> = <EXPRESSAO_FUNC> <END> 
 

<EXPRESSAO_ATT> = é
<EXPRESSAO_ATT> = <TYPE> <IDENTIFIER>



