<S> = <EXPRESSION> <END_LINE>
<S> = <EXPRESSION> <END_LINE> <S>

<EXPRESSION> = <BASIC_THINGS> <BASIC_OPERATOR> <BASIC_THINGS>

<BASIC_THINGS> = <NUMBER>
<BASIC_THINGS> = <IDENTIFIER> 

<BASIC_OPERATOR> = +
<BASIC_OPERATOR> = -

// a+b;a-c; 

