<S> =  <EPISILON>
<S> = <EXPRESSION> <END_LINE> <S>

<EXPRESSION> = <BASIC_THINGS> <BASIC_OPERATOR> <BASIC_THINGS>

<BASIC_THINGS> = <NUMBER>
<BASIC_THINGS> = <IDENTIFIER> 

<BASIC_OPERATOR> = +
<BASIC_OPERATOR> = -

<NUMBER> = a
<IDENTIFIER> = b
<END_LINE> = c
<EPISILON> =  ε

