<S> = <EXPRESSION> <END_LINE>

<EXPRESSION> = <PRIMARY_SEPARATOR_OPEN> <BASIC_ELEMENTS> <OPERATOR> <BASIC_ELEMENTS> <PRIMARY_SEPARATOR_CLOSE>
<EXPRESSION> = <PRIMARY_SEPARATOR_OPEN> <BASIC_ELEMENTS> <OPERATOR> <EXPRESSION> <PRIMARY_SEPARATOR_CLOSE>
<EXPRESSION> = <PRIMARY_SEPARATOR_OPEN> <EXPRESSION> <OPERATOR> <BASIC_ELEMENTS> <PRIMARY_SEPARATOR_CLOSE>

<END_LINE> = ;

<OPERATOR> = <BASIC_OPERATOR>
<OPERATOR> = <COMPLEX_OPERATOR>

<BASIC_OPERATOR> = -
<BASIC_OPERATOR> = +

<COMPLEX_OPERATOR> = /
<COMPLEX_OPERATOR> = *

<BASIC_ELEMENTS> = <NUMBER>
<BASIC_ELEMENTS> = <IDENTIFIER>

<PRIMARY_SEPARATOR_OPEN> = (
<PRIMARY_SEPARATOR_CLOSE> = )

// ((20*(A / (1*B)))+30);